In [1]:
import pandas as pd
import numpy as np

df_A = pd.DataFrame(data = np.random.rand(5, 4), columns = ["A", "B", "C", "D"], index = pd.date_range('20200101', periods = 5))
df_B = pd.DataFrame({"A" : ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11"],
"B" : ["B0", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11"],
"C" : ["C0", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11"],
"D" : ["D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "D11"]})

# 1. Pandas Series

In [ ]:
# Pandas Series
L = [1, 2, 3, 4, 5]

pd.Series(L)

0    1
1    2
2    3
3    4
4    5
dtype: int64

# 2. Pandas DataFrame

In [ ]:
# DataFrame 만들기 (1)
pd.DataFrame(data = np.random.rand(5, 4), columns = ["A",  "B",  "C",  "D"])

          A         B         C         D
0  0.983963  0.698438  0.517621  0.442860
1  0.577570  0.942560  0.004370  0.652429
2  0.743374  0.352698  0.329106  0.470845
3  0.160512  0.936799  0.785752  0.342699
4  0.173308  0.996954  0.622415  0.749618

In [ ]:
# Index 이름 지정하기
df_A = pd.DataFrame(data = np.random.rand(5, 4), columns = ["A", "B", "C", "D"])

date = pd.date_range('20200101', periods = 5)
df_A = df_A.set_index(date)
df_A

                   A         B         C         D
2020-01-01  0.976957  0.946928  0.774526  0.036631
2020-01-02  0.969293  0.961718  0.174202  0.445726
2020-01-03  0.925843  0.909875  0.007391  0.600045
2020-01-04  0.034623  0.896524  0.644903  0.016740
2020-01-05  0.084941  0.747614  0.756232  0.092963

In [ ]:
# DataFrame 만들기 (2)
data = {"A" : ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11"],
             "B" : ["B0", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11"],
             "C" : ["C0", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "C11"],
             "D" : ["D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "D11"]}
             
df_B = pd.DataFrame(data)
df_B

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [2]:
# DataFrame의 일부 행만 출력
df_B.head()

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [7]:
# DataFrame의 index, columns, values 추출
print(df_B.index)
print(df_B.columns)
print(df_B.values)

RangeIndex(start=0, stop=12, step=1)
Index(['A', 'B', 'C', 'D'], dtype='object')
[['A0' 'B0' 'C0' 'D0']
 ['A1' 'B1' 'C1' 'D1']
 ['A2' 'B2' 'C2' 'D2']
 ['A3' 'B3' 'C3' 'D3']
 ['A4' 'B4' 'C4' 'D4']
 ['A5' 'B5' 'C5' 'D5']
 ['A6' 'B6' 'C6' 'D6']
 ['A7' 'B7' 'C7' 'D7']
 ['A8' 'B8' 'C8' 'D8']
 ['A9' 'B9' 'C9' 'D9']
 ['A10' 'B10' 'C10' 'D10']
 ['A11' 'B11' 'C11' 'D11']]

In [10]:
# DataFrame의 요약정보 출력
df_B.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       12 non-null     object
 1   B       12 non-null     object
 2   C       12 non-null     object
 3   D       12 non-null     object
dtypes: object(4)
memory usage: 512.0+ bytes